apiVersion: v1
kind: Service
metadata:
  name: eureka-docker
  labels:
    run: eureka-docker
spec:
  selector:
    run: eureka-docker
  ports:
  - name: port1
    port: 1111
    targetPort: 1111
    protocol: TCP
  type: NodePort