apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: microservice-employee
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: microservice-employee
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        image: josemansilla/microservicio-employee:1
        name: microservice-employee
        resources: {}
      restartPolicy: Always
status: {}
