apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: microservice-empresa
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: microservice-empresa
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        image: josemansilla/microservcio_empresa:0.0.1
        name: microservice-empresa
        resources: {}
      restartPolicy: Always
status: {}
