apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb
    io.kompose.service: mongodb
  name: mongodb
spec:
 type: NodePort
 ports:
    - port: 27017
      name: port1
      targetPort: 27017
 selector:
   app: mongodb

