apiVersion: v1
kind: ReplicationController  
metadata:
  name: mongodb
  labels:
    purpose: mongodb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mongodb
        io.kompose.service: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        ports: 
        - containerPort: 27017
