# Configure this Discovery Server

eureka:
  instance: 
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    
server:
  port: 1111

spring:
  thymeleaf:
    enabled: false
  application:
    name: eureka-server
      
logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'      