spring:
  application:
    name: Employee
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/microserviceblog

  metrics:
    export:
      delay-millis: 5000
      enabled: true
      includes: heap.used,heap.committed,mem,mem.free,threads,systemload.average,counter.status.2*.*,counter.status.5*.*
      #,datasource.primary.active,datasource.primary.usage,gauge.response.employee

logging:
  level:
    org.influxdb: DEBUG
    
endpoints:
  actuator:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false

server:
  port: 0
      
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:1111/eureka/      
  instance:
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}  
      
      
---

spring:
  profiles: docker
 
  data:
    mongodb:
      uri: mongodb://mongodb/microserviceblog
#      host: mongodocker
#      port: 2020
#      database: microserviceblog

  
eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka-docker:1111/eureka/      
  instance:
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}      