spring:
  application:
    name: EdgeService
   
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8075/eureka/
      
server:
  port: 8085
 
zuul:
  prefix: /api/rest
  strip-prefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000  
            
---

spring:
  profiles: docker
  
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka-docker:8075/eureka/  